name: Development Build

on:
  pull_request:
    branches: [dev]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Install iOS workload # still required
        run: dotnet workload install ios

      - name: Restore
        run: dotnet restore FacebookiOSBindings.sln # workload restore no longer needed

      - name: Build
        run: dotnet build FacebookiOSBindings.Tests/FacebookiOSBindings.Tests.csproj -c Debug

      - name: Test (simulator)
        run: dotnet test FacebookiOSBindings.Tests/FacebookiOSBindings.Tests.csproj -c Debug --filter "Category!=RequiresActualSDK"
