name: Development Build

on:
  pull_request:
    branches: [dev]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
    
      - name: Install iOS workload
        run: dotnet workload install ios

      - name: Restore RID
        run: dotnet workload restore FacebookiOSBindings.Tests/FacebookiOSBindings.Tests.csproj -p:RuntimeIdentifier=iossimulator-arm64 

      - name: Restore NuGet
        run: dotnet restore FacebookiOSBindings.Tests/FacebookiOSBindings.Tests.csproj --runtime iossimulator-arm64

      - name: Build binding
        run: dotnet build FacebookiOSBindings/FacebookiOSBindings.csproj -c Debug
      
      - name: Build tests
        run: dotnet build FacebookiOSBindings.Tests/FacebookiOSBindings.Tests.csproj -c Debug -p:RuntimeIdentifier=iossimulator-arm64 -p:EnableCodeSigning=false
      
      - name: Run Unit Tests
        run: dotnet test FacebookiOSBindings.Tests/FacebookiOSBindings.Tests.csproj --configuration Debug --no-build --filter "Category!=RequiresActualSDK"
