name: Development Build

on:
  pull_request:
    branches: [dev]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/FacebookiOSBindings.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Cache iOS workload
        uses: actions/cache@v4
        with:
          path: |
            ~/.dotnet/workloads
            ~/.dotnet/sdk-manifests
          key: ${{ runner.os }}-ios-workload-${{ hashFiles('FacebookiOSBindings/FacebookiOSBindings.csproj') }}
          restore-keys: |
            ${{ runner.os }}-ios-workload-

      - name: Install iOS workload
        run: dotnet workload install ios

      - name: Install maui workload
        run: dotnet workload install maui-tizen

      - name: Restore dependencies
        run: dotnet restore FacebookiOSBindings.sln

      - name: Build
        run: dotnet build FacebookiOSBindings.sln --configuration Debug --no-restore

      - name: Run Unit Tests
        run: dotnet test FacebookiOSBindings.Tests/FacebookiOSBindings.Tests.csproj --configuration Debug --no-build --filter "Category!=RequiresActualSDK"
